### ISSUE TITLE
Can't import modules

### ISSUE THREAD

**Issue by Dugy** [Nelarius/wrenpp#6]
I have embedded wren into my program, it mostly works, but problems start to happen when I try to import my module (originally meant for declaring foreign functions, but I realised that the same problem appears also with simple classes).

First I bind classes and methods, then I create the virtual machine (doing it in the other order caused the program to hand indefinitely with no warning), then I import the module (using the import command in wren, I also tried executeModule to no avail), everything seems all right, but when I try to use a constructor from there (even if everything foreign is commented), it tells me that _(class name) variable is used but not defined_.  It appears like if the module wasn't loaded at all, but I have checked that my loadModuleFn loads the correct code (incorrect code reliably causes trouble).

Here is the dummy code I used (it worked fine in the online IDE):
`class Vec2 {`
`	setX(x) { _x = x}`
`	setY(Y) { _y = y}`
`	x {_x}`
`	y {_y}`
`	construct new(x, y) {`
`		_x = x`
`		_y = y`
`	}`
`	static print(v) {`
`	    System.print("%(v.x) , %(v.y)")`
`	}`
`}`
(sorry, markdown removes indentation) I am running it using the vm::executeString command. In this case, it is:
`import "game"`
`var v = Vec2(1, 1)` // Error

**Comment by Nelarius** [comment]
Yeah, there's nothing wrong with your `Vec2` itself, however:

```js
// you have to explicitly tell Wren which variables get imported
// this is the cause for your "used but not defined" error
import "game" for Vec2

// call with your named constructor
var v = Vec2.new(1, 1)
```

Here's a small working example.

Let's have your definition `Vec2` live in a file called  `game.wren`.

```js
foreign class Vec2 {
    construct new(x, y) {}

    foreign x
    foreign x=(x)
    foreign y
    foreign y=(y)
}
```

Here's a small C++ source file which implements the foreign type `Vec2` and instantiates it:
```cpp
#include "Wren++.h"

struct Vec2 {
    float x, y;
};

int main(int argc, char** argv) {
    wrenpp::beginModule("game")
        .bindClass<Vec2, float, float>("Vec2")
            .bindGetter<decltype(Vec2::x), &Vec2::x>("x")
            .bindSetter<decltype(Vec2::x), &Vec2::x>("x=(_)")
            .bindGetter<decltype(Vec2::y), &Vec2::y>("y")
            .bindSetter<decltype(Vec2::y), &Vec2::y>("y=(_)");

    wrenpp::VM vm;
    vm.executeString("import \"game\" for Vec2\n");
    vm.executeString("var v = Vec2.new(2.0, 1.0)\n");
    vm.executeString("System.print(\"v: %(v.x), %(v.y)\")");

    return 0;
}
```

You definitely have to bind the methods before you instantiate a VM and execute code -- otherwise the VM won't be able to find the methods and types that you bound. I probably need to mention that in the docs 😅

**Comment by Dugy** [comment]
Yeah, it does the trick. I thought it refers to variables only, not classes.

Right after fixing it, I came to another problem, trying to bind methods that take a `const std::string&` as argument cause segfault. However, after removing that reference, it started to work. Now I can use static methods to create wren wrappers to entities in my program and call their methods.

I think that the introduction would also need a mention about that const std::string& problem (I haven't tried other references).

**Comment by Nelarius** [comment]
Ok, I got a segfault on `const std::string&` arguments as well. I will close this issue, and open a new one for the string issue.

**Comment by Nelarius** [comment]
Hey, I added a template specialization for `const std::string&` arguments, so those arguments should work now. Note, however, that despite being a reference, an  `std::string` still gets constructed because strings are passed from Wren as `const char*`. So ideally, a C++ API facing Wren would just take `std::string` arguments.
